/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalahorcado;
import javax.swing.*;
import java.util.*;
/**
 *
 * @author coron
 */
public class form4 extends javax.swing.JFrame {

    /**
     * Creates new form form4
     */
    public form4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonM = new javax.swing.JButton();
        letraAst1M = new javax.swing.JLabel();
        letraAst2M = new javax.swing.JLabel();
        letraAst3M = new javax.swing.JLabel();
        letraAst4M = new javax.swing.JLabel();
        letraAst5M = new javax.swing.JLabel();
        imErrorM = new javax.swing.JLabel();
        vida1M = new javax.swing.JLabel();
        vida2M = new javax.swing.JLabel();
        vida3M = new javax.swing.JLabel();
        ingJug = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        botonM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/botonCorroborar.png"))); // NOI18N
        botonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMActionPerformed(evt);
            }
        });
        getContentPane().add(botonM);
        botonM.setBounds(193, 374, 98, 85);

        letraAst1M.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/letraAst.png"))); // NOI18N
        getContentPane().add(letraAst1M);
        letraAst1M.setBounds(16, 248, 96, 72);

        letraAst2M.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/letraAst.png"))); // NOI18N
        getContentPane().add(letraAst2M);
        letraAst2M.setBounds(118, 240, 96, 80);

        letraAst3M.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/letraAst.png"))); // NOI18N
        getContentPane().add(letraAst3M);
        letraAst3M.setBounds(220, 243, 85, 77);

        letraAst4M.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/letraAst.png"))); // NOI18N
        getContentPane().add(letraAst4M);
        letraAst4M.setBounds(311, 232, 82, 88);

        letraAst5M.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/letraAst.png"))); // NOI18N
        getContentPane().add(letraAst5M);
        letraAst5M.setBounds(399, 241, 88, 79);

        imErrorM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/imagenError.png"))); // NOI18N
        getContentPane().add(imErrorM);
        imErrorM.setBounds(24, 114, 100, 100);

        vida1M.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/vidas.png"))); // NOI18N
        getContentPane().add(vida1M);
        vida1M.setBounds(153, 134, 80, 80);

        vida2M.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/vidas.png"))); // NOI18N
        getContentPane().add(vida2M);
        vida2M.setBounds(239, 134, 80, 80);

        vida3M.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/vidas.png"))); // NOI18N
        getContentPane().add(vida3M);
        vida3M.setBounds(325, 134, 80, 80);

        ingJug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingJugActionPerformed(evt);
            }
        });
        getContentPane().add(ingJug);
        ingJug.setBounds(220, 331, 53, 32);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/botonApag.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(447, 30, 97, 73);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/botonAtras.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(332, 30, 97, 73);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/fondoJuego.jpeg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 570, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents
Random rnd = new Random();
int errorF=0, error=0,puntos, azar;
String [][] palabraM={{"M","O","S","C","A"},{"M","O","U","S","E"},{"C","I","N","T","A"},{"B","A","R","C","O"}};
    private void botonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMActionPerformed
       letraAst1M.setVisible(true);
        letraAst2M.setVisible(true);
        letraAst3M.setVisible(true);
        letraAst4M.setVisible(true);
        letraAst5M.setVisible(true);
        imErrorM.setVisible(true);
        vida1M.setVisible(true);
        vida2M.setVisible(true);
        vida3M.setVisible(true);
        String letra, letraError;
       from6 f6 = new from6();
        form7 f7 = new form7();
        Icon icono;
        
        azar = rnd.nextInt(4);
        switch(azar){
        case 0:
            letra=ingJug.getText();
            for(int i=0; i < palabraM[0].length; i++){
                if(palabraM[0][i].equalsIgnoreCase(letra)){
                    switch(letra){
                        case "m":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraM.png"));
                            letraAst1M.setIcon(icono);
                            break;
                        case "o":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraO.png"));
                            letraAst2M.setIcon(icono);
                            break;
                        case "s":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraS.png"));
                            letraAst3M.setIcon(icono);
                            break;
                            case "c":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraC.png"));
                            letraAst4M.setIcon(icono);
                            break;
                        case "a":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraA.png"));
                            letraAst5M.setIcon(icono);
                            break;
                        
                    }
                }else{
                    error +=1;
                }
                errorF = error / 5;
                
            }
            if(errorF == 1){
                icono = new ImageIcon(getClass().getResource("/imag/vidaPerdida.png"));
               vida1M.setIcon(icono);
               icono = new ImageIcon(getClass().getResource("/imag/imagenError1.png"));
               imErrorM.setIcon(icono);
            }else{
                if(errorF == 2){
                icono = new ImageIcon(getClass().getResource("/imag/vidaPerdida.png"));
               vida2M.setIcon(icono);
               icono = new ImageIcon(getClass().getResource("/imag/imagenError2.png"));
               imErrorM.setIcon(icono);
                }else{
                    if(errorF == 3){
                icono = new ImageIcon(getClass().getResource("/imag/vidaPerdida.png"));
               vida2M.setIcon(icono);
               icono = new ImageIcon(getClass().getResource("/imag/imagenError3.png"));
               imErrorM.setIcon(icono);
               f6.setVisible(true);
                this.dispose();
                    }else{
                        if(puntos >= 4){
                            
       f7.setVisible(true);
       this.dispose();
                        }
                    }
                }
            }
        break;
        case 1:
            letra=ingJug.getText();
            for(int i=0; i < palabraM[1].length; i++){
                if(palabraM[1][i].equalsIgnoreCase(letra)){
                    switch(letra){
                        case "m":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraM.png"));
                            letraAst1M.setIcon(icono);
                            break;
                        case "o":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraO.png"));
                            letraAst2M.setIcon(icono);
                            break;
                        case "u":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraU.png"));
                            letraAst3M.setIcon(icono);
                            break;
                        case "s":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraS.png"));
                            letraAst4M.setIcon(icono);
                            break;
                            case "e":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraE.png"));
                            letraAst5M.setIcon(icono);
                            break;
                        
                    }
                }else{
                    error +=1;
                }
                errorF = error / 5;
                
            }
            if(errorF == 1){
                icono = new ImageIcon(getClass().getResource("/imag/vidaPerdida.png"));
               vida1M.setIcon(icono);
               icono = new ImageIcon(getClass().getResource("/imag/imagenError1.png"));
               imErrorM.setIcon(icono);
            }else{
                if(errorF == 2){
                icono = new ImageIcon(getClass().getResource("/imag/vidaPerdida.png"));
               vida2M.setIcon(icono);
               icono = new ImageIcon(getClass().getResource("/imag/imagenError2.png"));
               imErrorM.setIcon(icono);
                }else{
                    if(errorF == 3){
                icono = new ImageIcon(getClass().getResource("/imag/vidaPerdida.png"));
               vida2M.setIcon(icono);
               icono = new ImageIcon(getClass().getResource("/imag/imagenError3.png"));
               imErrorM.setIcon(icono);
               f6.setVisible(true);
                this.dispose();
                    }else{
                        if(puntos >= 4){
                            
       f7.setVisible(true);
       this.dispose();
                        }
                    }
                }
            }
        break;
        case 2:
            letra=ingJug.getText();
            for(int i=0; i < palabraM[2].length; i++){
                if(palabraM[2][i].equalsIgnoreCase(letra)){
                    switch(letra){
                        case "c":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraC.png"));
                            letraAst1M.setIcon(icono);
                            break;
                        case "i":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraI.png"));
                            letraAst2M.setIcon(icono);
                            break;
                        case "n":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraN.png"));
                            letraAst3M.setIcon(icono);
                            break;
                        case "t":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraT.png"));
                            letraAst4M.setIcon(icono);
                            break;
                            case "a":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraA.png"));
                            letraAst5M.setIcon(icono);
                            break;
                        
                    }
                }else{
                    error +=1;
                }
                errorF = error / 5;
                
            }
            if(errorF == 1){
                icono = new ImageIcon(getClass().getResource("/imag/vidaPerdida.png"));
               vida1M.setIcon(icono);
               icono = new ImageIcon(getClass().getResource("/imag/imagenError1.png"));
               imErrorM.setIcon(icono);
            }else{
                if(errorF == 2){
                icono = new ImageIcon(getClass().getResource("/imag/vidaPerdida.png"));
               vida2M.setIcon(icono);
               icono = new ImageIcon(getClass().getResource("/imag/imagenError2.png"));
               imErrorM.setIcon(icono);
                }else{
                    if(errorF == 3){
                icono = new ImageIcon(getClass().getResource("/imag/vidaPerdida.png"));
               vida2M.setIcon(icono);
               icono = new ImageIcon(getClass().getResource("/imag/imagenError3.png"));
               imErrorM.setIcon(icono);
               f6.setVisible(true);
                this.dispose();
                    }else{
                        if(puntos >= 4){
                            
       f7.setVisible(true);
       this.dispose();
                        }
                    }
                }
            }
        break;
        case 3:
            letra=ingJug.getText();
            for(int i=0; i < palabraM[3].length; i++){
                if(palabraM[3][i].equalsIgnoreCase(letra)){
                    switch(letra){
                        case "b":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraB.png"));
                            letraAst1M.setIcon(icono);
                            break;
                        case "a":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraA.png"));
                            letraAst2M.setIcon(icono);
                            break;
                        case "r":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraR.png"));
                            letraAst3M.setIcon(icono);
                            break;
                            case "c":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraC.png"));
                            letraAst4M.setIcon(icono);
                            break;
                        case "o":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraO.png"));
                            letraAst5M.setIcon(icono);
                            break;
                        
                    }
                }else{
                    error +=1;
                }
                errorF = error / 5;
                
            }
            if(errorF == 1){
                icono = new ImageIcon(getClass().getResource("/imag/vidaPerdida.png"));
               vida1M.setIcon(icono);
               icono = new ImageIcon(getClass().getResource("/imag/imagenError1.png"));
               imErrorM.setIcon(icono);
            }else{
                if(errorF == 2){
                icono = new ImageIcon(getClass().getResource("/imag/vidaPerdida.png"));
               vida2M.setIcon(icono);
               icono = new ImageIcon(getClass().getResource("/imag/imagenError2.png"));
               imErrorM.setIcon(icono);
                }else{
                    if(errorF == 3){
                icono = new ImageIcon(getClass().getResource("/imag/vidaPerdida.png"));
               vida2M.setIcon(icono);
               icono = new ImageIcon(getClass().getResource("/imag/imagenError3.png"));
               imErrorM.setIcon(icono);
               f6.setVisible(true);
                this.dispose();
                    }else{
                        if(puntos >= 4){
                            
       f7.setVisible(true);
       this.dispose();
                        }
                    }
                }
            }
        break;
        
    }
    }//GEN-LAST:event_botonMActionPerformed

    private void ingJugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingJugActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingJugActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        form2 f2 = new form2();
        f2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonM;
    private javax.swing.JLabel imErrorM;
    private javax.swing.JTextField ingJug;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel letraAst1M;
    private javax.swing.JLabel letraAst2M;
    private javax.swing.JLabel letraAst3M;
    private javax.swing.JLabel letraAst4M;
    private javax.swing.JLabel letraAst5M;
    private javax.swing.JLabel vida1M;
    private javax.swing.JLabel vida2M;
    private javax.swing.JLabel vida3M;
    // End of variables declaration//GEN-END:variables
}
