/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalahorcado;
import javax.swing.*;
import java.util.*;
/**
 *
 * @author coron
 */
public class form3 extends javax.swing.JFrame {

    /**
     * Creates new form form3
     */
    public form3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonF = new javax.swing.JButton();
        letraAst1F = new javax.swing.JLabel();
        letraAst2F = new javax.swing.JLabel();
        letraAst3F = new javax.swing.JLabel();
        letraAst4F = new javax.swing.JLabel();
        imErrorF = new javax.swing.JLabel();
        vida1F = new javax.swing.JLabel();
        vida2F = new javax.swing.JLabel();
        vida3F = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ingJug = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        botonF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/botonCorroborar.png"))); // NOI18N
        botonF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFActionPerformed(evt);
            }
        });
        getContentPane().add(botonF);
        botonF.setBounds(190, 330, 160, 82);

        letraAst1F.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/letraAst.png"))); // NOI18N
        getContentPane().add(letraAst1F);
        letraAst1F.setBounds(86, 180, 96, 70);

        letraAst2F.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/letraAst.png"))); // NOI18N
        getContentPane().add(letraAst2F);
        letraAst2F.setBounds(180, 180, 100, 70);

        letraAst3F.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/letraAst.png"))); // NOI18N
        getContentPane().add(letraAst3F);
        letraAst3F.setBounds(270, 180, 96, 70);

        letraAst4F.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/letraAst.png"))); // NOI18N
        getContentPane().add(letraAst4F);
        letraAst4F.setBounds(360, 180, 96, 70);

        imErrorF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/imagenError.png"))); // NOI18N
        getContentPane().add(imErrorF);
        imErrorF.setBounds(50, 60, 100, 100);

        vida1F.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/vidas.png"))); // NOI18N
        getContentPane().add(vida1F);
        vida1F.setBounds(180, 90, 80, 69);

        vida2F.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/vidas.png"))); // NOI18N
        getContentPane().add(vida2F);
        vida2F.setBounds(270, 90, 80, 70);

        vida3F.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/vidas.png"))); // NOI18N
        getContentPane().add(vida3F);
        vida3F.setBounds(360, 90, 80, 70);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/botonApag.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(478, 11, 80, 70);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/botonAtras.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(392, 11, 80, 70);
        getContentPane().add(ingJug);
        ingJug.setBounds(220, 270, 110, 45);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/fondoJuego.jpeg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 570, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        form2 f2 = new form2();
        f2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
Random rnd = new Random();
int errorF=0, error=0,puntos, azar;
String [][] palabraF={{"M","E","S","A"},{"T","A","Z","O"},{"V","A","S","O"},{"G","A","T","O"}};
    private void botonFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFActionPerformed
        letraAst1F.setVisible(true);
        letraAst2F.setVisible(true);
        letraAst3F.setVisible(true);
        letraAst4F.setVisible(true);
        imErrorF.setVisible(true);
        vida1F.setVisible(true);
        vida2F.setVisible(true);
        vida3F.setVisible(true);
        String letra, letraError;
       from6 f6 = new from6();
        form7 f7 = new form7();
        Icon icono;
        
        azar = rnd.nextInt(4);
        switch(azar){
        case 0:
            letra=ingJug.getText();
            for(int i=0; i < palabraF[0].length; i++){
                if(palabraF[0][i].equalsIgnoreCase(letra)){
                    switch(letra){
                        case "m":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraM.png"));
                            letraAst1F.setIcon(icono);
                            break;
                        case "e":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraE.png"));
                            letraAst2F.setIcon(icono);
                            break;
                        case "s":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraS.png"));
                            letraAst3F.setIcon(icono);
                            break;
                        case "a":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraA.png"));
                            letraAst4F.setIcon(icono);
                            break;
                        
                    }
                }else{
                    error +=1;
                }
                errorF = error / 4;
                
            }
            if(errorF == 1){
                icono = new ImageIcon(getClass().getResource("/imag/vidaPerdida.png"));
               vida1F.setIcon(icono);
               icono = new ImageIcon(getClass().getResource("/imag/imagenError1.png"));
               imErrorF.setIcon(icono);
            }else{
                if(errorF == 2){
                icono = new ImageIcon(getClass().getResource("/imag/vidaPerdida.png"));
               vida2F.setIcon(icono);
               icono = new ImageIcon(getClass().getResource("/imag/imagenError2.png"));
               imErrorF.setIcon(icono);
                }else{
                    if(errorF == 3){
                icono = new ImageIcon(getClass().getResource("/imag/vidaPerdida.png"));
               vida2F.setIcon(icono);
               icono = new ImageIcon(getClass().getResource("/imag/imagenError3.png"));
               imErrorF.setIcon(icono);
               f6.setVisible(true);
                this.dispose();
                    }else{
                        if(puntos >= 4){
                            
       f7.setVisible(true);
       this.dispose();
                        }
                    }
                }
            }
        break;
        case 1:
            letra=ingJug.getText();
            for(int i=0; i < palabraF[1].length; i++){
                if(palabraF[1][i].equalsIgnoreCase(letra)){
                    switch(letra){
                        case "t":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraT.png"));
                            letraAst1F.setIcon(icono);
                            break;
                        case "a":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraA.png"));
                            letraAst2F.setIcon(icono);
                            break;
                        case "z":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraZ.png"));
                            letraAst3F.setIcon(icono);
                            break;
                        case "0":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraO.png"));
                            letraAst4F.setIcon(icono);
                            break;
                        
                    }
                }else{
                    error +=1;
                }
                errorF = error / 4;
                
            }
            if(errorF == 1){
                icono = new ImageIcon(getClass().getResource("/imag/vidaPerdida.png"));
               vida1F.setIcon(icono);
               icono = new ImageIcon(getClass().getResource("/imag/imagenError1.png"));
               imErrorF.setIcon(icono);
            }else{
                if(errorF == 2){
                icono = new ImageIcon(getClass().getResource("/imag/vidaPerdida.png"));
               vida2F.setIcon(icono);
               icono = new ImageIcon(getClass().getResource("/imag/imagenError2.png"));
               imErrorF.setIcon(icono);
                }else{
                    if(errorF == 3){
                icono = new ImageIcon(getClass().getResource("/imag/vidaPerdida.png"));
               vida2F.setIcon(icono);
               icono = new ImageIcon(getClass().getResource("/imag/imagenError3.png"));
               imErrorF.setIcon(icono);
               f6.setVisible(true);
                this.dispose();
                    }else{
                        if(puntos >= 4){
                            
       f7.setVisible(true);
       this.dispose();
                        }
                    }
                }
            }
        break;
        case 2:
            letra=ingJug.getText();
            for(int i=0; i < palabraF[2].length; i++){
                if(palabraF[2][i].equalsIgnoreCase(letra)){
                    switch(letra){
                        case "v":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraV.png"));
                            letraAst1F.setIcon(icono);
                            break;
                        case "a":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraA.png"));
                            letraAst2F.setIcon(icono);
                            break;
                        case "s":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraS.png"));
                            letraAst3F.setIcon(icono);
                            break;
                        case "o":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraO.png"));
                            letraAst4F.setIcon(icono);
                            break;
                        
                    }
                }else{
                    error +=1;
                }
                errorF = error / 4;
                
            }
            if(errorF == 1){
                icono = new ImageIcon(getClass().getResource("/imag/vidaPerdida.png"));
               vida1F.setIcon(icono);
               icono = new ImageIcon(getClass().getResource("/imag/imagenError1.png"));
               imErrorF.setIcon(icono);
            }else{
                if(errorF == 2){
                icono = new ImageIcon(getClass().getResource("/imag/vidaPerdida.png"));
               vida2F.setIcon(icono);
               icono = new ImageIcon(getClass().getResource("/imag/imagenError2.png"));
               imErrorF.setIcon(icono);
                }else{
                    if(errorF == 3){
                icono = new ImageIcon(getClass().getResource("/imag/vidaPerdida.png"));
               vida2F.setIcon(icono);
               icono = new ImageIcon(getClass().getResource("/imag/imagenError3.png"));
               imErrorF.setIcon(icono);
               f6.setVisible(true);
                this.dispose();
                    }else{
                        if(puntos >= 4){
                            
       f7.setVisible(true);
       this.dispose();
                        }
                    }
                }
            }
        break;
        case 3:
            letra=ingJug.getText();
            for(int i=0; i < palabraF[3].length; i++){
                if(palabraF[3][i].equalsIgnoreCase(letra)){
                    switch(letra){
                        case "g":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraG.png"));
                            letraAst1F.setIcon(icono);
                            break;
                        case "a":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraA.png"));
                            letraAst2F.setIcon(icono);
                            break;
                        case "t":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraT.png"));
                            letraAst3F.setIcon(icono);
                            break;
                        case "o":
                            puntos +=1;
                            error=0;
                            icono = new ImageIcon(getClass().getResource("/imag/letraO.png"));
                            letraAst4F.setIcon(icono);
                            break;
                        
                    }
                }else{
                    error +=1;
                }
                errorF = error / 4;
                
            }
            if(errorF == 1){
                icono = new ImageIcon(getClass().getResource("/imag/vidaPerdida.png"));
               vida1F.setIcon(icono);
               icono = new ImageIcon(getClass().getResource("/imag/imagenError1.png"));
               imErrorF.setIcon(icono);
            }else{
                if(errorF == 2){
                icono = new ImageIcon(getClass().getResource("/imag/vidaPerdida.png"));
               vida2F.setIcon(icono);
               icono = new ImageIcon(getClass().getResource("/imag/imagenError2.png"));
               imErrorF.setIcon(icono);
                }else{
                    if(errorF == 3){
                icono = new ImageIcon(getClass().getResource("/imag/vidaPerdida.png"));
               vida2F.setIcon(icono);
               icono = new ImageIcon(getClass().getResource("/imag/imagenError3.png"));
               imErrorF.setIcon(icono);
               f6.setVisible(true);
                this.dispose();
                    }else{
                        if(puntos >= 4){
                            
       f7.setVisible(true);
       this.dispose();
                        }
                    }
                }
            }
        break;
        
    }
    }//GEN-LAST:event_botonFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonF;
    private javax.swing.JLabel imErrorF;
    private javax.swing.JTextField ingJug;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel letraAst1F;
    private javax.swing.JLabel letraAst2F;
    private javax.swing.JLabel letraAst3F;
    private javax.swing.JLabel letraAst4F;
    private javax.swing.JLabel vida1F;
    private javax.swing.JLabel vida2F;
    private javax.swing.JLabel vida3F;
    // End of variables declaration//GEN-END:variables
}
